# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-23 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingOfTheHill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='king',
            name='coronation',
            field=models.DateTimeField(),
        ),
    ]
