# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-16 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kingOfTheHill', '0005_auto_20190314_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField(null=True)),
                ('tournament_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentFight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=120)),
                ('player2', models.CharField(max_length=120)),
                ('winner', models.CharField(max_length=120, null=True)),
                ('margin', models.IntegerField(default=-1, null=True)),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kingOfTheHill.Tournament')),
            ],
        ),
    ]
