# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-16 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingOfTheHill', '0006_tournament_tournamentfight'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentfight',
            name='level',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='tournamentfight',
            name='margin',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
