# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-16 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kingOfTheHill', '0007_auto_20190316_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentfight',
            name='tournament_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights', to='kingOfTheHill.Tournament'),
        ),
    ]
