# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingOfTheHill', '0009_auto_20190317_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='', max_length=120),
        ),
    ]
