# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingOfTheHill', '0011_auto_20190318_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField(null=True)),
                ('tournament_id', models.AutoField(primary_key=True, serialize=False)),
                ('num_game', models.IntegerField(default=1)),
                ('max_round', models.IntegerField(default=1000)),
                ('initial_stack', models.IntegerField(default=10000)),
                ('smallblind_amount', models.IntegerField(default=20)),
            ],
        ),
    ]
