# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-06 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kingOfTheHill', '0012_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=500)),
                ('time', models.DateField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='kingOfTheHill.Tournament')),
            ],
        ),
    ]
