# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-06 03:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kingOfTheHill', '0013_groupupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupupload',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL),
        ),
    ]
