# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-06 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingOfTheHill', '0014_auto_20190406_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupupload',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
