# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-23 07:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kingOfTheHill', '0015_auto_20190406_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalTournamentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(max_length=120)),
                ('profit', models.IntegerField(default=0, null=True)),
                ('loser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losses', to=settings.AUTH_USER_MODEL)),
                ('winner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
