# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-23 09:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kingOfTheHill', '0016_finaltournamentresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaltournamentresult',
            name='loser_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='losses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='finaltournamentresult',
            name='winner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wins', to=settings.AUTH_USER_MODEL),
        ),
    ]
