# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-26 11:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kingOfTheHill', '0017_auto_20190423_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final2TournamentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(max_length=120)),
                ('profit', models.IntegerField(default=0, null=True)),
                ('loser_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='losses2', to=settings.AUTH_USER_MODEL)),
                ('winner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wins2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinalTournament',
            fields=[
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField(null=True)),
                ('tournament_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FinalTournamentFight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(max_length=120)),
                ('winner', models.CharField(max_length=120, null=True)),
                ('reward', models.IntegerField(default=0, null=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finalFights1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finalFights2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
